#!/usr/bin/env bash

set -e

function phpunit()
{
	cwd="$(pwd)"
	cd "$1"
	../../../vendor/bin/phpunit --verbose
	cd "$cwd"
}

if [[ -n "$MODULE" ]]
then
	dir="module/$MODULE/test"
	if [[ ! -d "$dir" ]]
	then
		echo "Test directory does not exist for $dir"
		exit 1
	fi
	phpunit "$dir"
else
	for dir in module/*/test
	do
		phpunit "$dir"
	done
fi
